#!/usr/bin/env node
import _fs from 'fs';
const { version } = require("../package.json");



const fs = _fs.promises;


const doesFileNeedChange = (newFilePath: string, content: string) => {
    return content !== _fs.readFileSync(newFilePath).toString();
}


const exportAll = async (path: string, force: string): Promise<string | undefined> => {

    const dir = await fs.readdir(path);

    const fileName = path.split('/').pop();

    const length = dir.length;

    const files: Array<string> = [];

    for (let i = 0; i < length; i++) {



        const stat = await fs.stat(path + '/' + dir[i]);

        if (stat.isDirectory()) {
            const exportFile = await exportAll(path + '/' + dir[i], force);

            if (exportFile) {
                files.push(exportFile);
            }
        }

        if (force !== "-f" && (dir[i].endsWith('.freezed.dart') || dir[i].endsWith('.g.dart'))) {
            console.log("ignoring ", dir[i], '   you can force this to be generated by adding "-f" to the command');
            continue;
        }

        if (dir[i].endsWith('.dart') && !dir[i].endsWith('_' + fileName + '.dart')) {
            files.push(dir[i]);
        }

    }

    if (files.length == 0) return;

    const fileExtension = '.dart';
    const filePath = `${path}/_${fileName}${fileExtension}`;
    const content = files.map((e) => `export '${e}';\n`).join('');


    if (doesFileNeedChange(filePath, content) === false) {
        // console.log("No change required");
        return;
    }
    await _fs.writeFile(filePath, content, _ => _);

    console.log('exported --> ', filePath);

    return `./${fileName}/_${fileName}${fileExtension}`;
}

const statExport = async () => {
    const [_, __, path, ...args] = process.argv;

    if (path === "-v" || path === "--version") {
        return console.log('Dart Export version ', version);
    }

    if (!path) return console.log("No Path Provider");

    const force = args.find((e) => e === "-f") ?? '';
    const watch = args.find((e) => e === "-w") ?? '';

    console.log("Exporting")

    console.log('export from: ', path);

    await exportAll(path, force);

    if (watch) {
        console.log('Watching Directory for changes');
        _fs.watch(path, { recursive: true, persistent: true }, (event, file) => {
            // console.log("Event: ", event, ". File: ", file);
            exportAll(path, force);
        })
    }


}

statExport();
